"""Generate kaggle/kernel.py (self-contained: repo scripts embedded base64) + kernel-metadata.json.

Re-run after any repo script change, then: kaggle kernels push -p kaggle -t 18000 --accelerator NvidiaTeslaT4
"""
import base64
import json
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / "kaggle"
SCRIPTS = ["data_prep.py", "verbalize.py", "eval.py", "model.py", "train_phase2.py"]

TEMPLATE = '''# GENERATED by build_kernel.py — edit the repo scripts, then regenerate. Do not edit by hand.
import base64
import os
import subprocess
import sys

SCRIPTS = {scripts!r}

for name, blob in SCRIPTS.items():
    with open(name, "wb") as f:
        f.write(base64.b64decode(blob))

os.makedirs("data", exist_ok=True)


def run(cmd):
    print("+", " ".join(cmd), flush=True)
    r = subprocess.run(cmd)
    if r.returncode != 0:
        sys.exit(f"FAILED: {{' '.join(cmd)}}")


run(["wget", "-q", "https://files.grouplens.org/datasets/movielens/ml-1m.zip", "-O", "data/ml-1m.zip"])
run([sys.executable, "data_prep.py"])
# preflight smoke (~15 min incl. Qwen download) — aborts the kernel before wasting a full run if something is broken
run([sys.executable, "train_phase2.py", "--max-examples", "400", "--epochs", "1", "--batch", "2",
     "--accum", "4", "--val-users", "200", "--out", "runs/smoke"])
# full base run (~2-3h), resumable if the session is ever restarted
run([sys.executable, "train_phase2.py", "--resume", "--out", "runs/phase2_base"])
run([sys.executable, "-c", EVAL_SNIPPET])
'''

EVAL_SNIPPET = '''import json
import eval as eval_lib
from model import GenRecModel, genrec_scorer, load_tokenizer

tok = load_tokenizer()
catalog_map = {c["item_id"]: c for c in map(json.loads, open("data/catalog.jsonl"))}
_, users = eval_lib.load_all("data")
model, step = GenRecModel.from_ckpt("runs/phase2_base")
m = eval_lib.evaluate(genrec_scorer(model, tok, catalog_map), users, "test")
print("FINAL_EVAL " + json.dumps({"scorer": "genrec", "ckpt_step": step, **m}))'''

def main():
    OUT.mkdir(exist_ok=True)
    embedded = {s: base64.b64encode((ROOT / s).read_bytes()).decode() for s in SCRIPTS}
    body = TEMPLATE.format(scripts=embedded).replace("run([sys.executable, \"-c\", EVAL_SNIPPET])",
                                                     "run([sys.executable, \"-c\", " + repr(EVAL_SNIPPET) + "])")
    (OUT / "kernel.py").write_text(body)
    meta = {
        "id": "eros438/genrec-phase2",
        "title": "genrec phase2",
        "code_file": "kernel.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": True,
        "machine_shape": "NvidiaTeslaT4",
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
        "model_sources": [],
    }
    (OUT / "kernel-metadata.json").write_text(json.dumps(meta, indent=2))
    print(f"wrote {OUT}/kernel.py ({len(body)//1024}KB) + kernel-metadata.json")

if __name__ == "__main__":
    main()
